# Generated by Django 2.0.4 on 2018-07-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20180708_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=50)),
                ('edu_type', models.CharField(max_length=50)),
                ('edu_uni', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Employee')),
            ],
        ),
    ]
